/**
 * The Modulo Fight roster.
 *
 * Each entry is a fully self-contained `FighterConfig`. Stats are deliberately
 * balanced so that **no fighter strictly dominates another** — every character
 * trades a strength for a weakness (verified: no Pareto-dominant pair). Robin is
 * the true median, so they neither dominate nor are dominated by anyone.
 *
 * Beyond raw stats, fighters differ in *mobility feel* via optional
 * `airControl` and `gravityMul`: acrobats (Till) float and steer hard in the
 * air, speedsters (Leif) are nimble, and heavies (Leonidas, Tusya) fast-fall
 * and drift like bricks. Every fighter's jump is tuned so a double jump can
 * reach every platform on every stage — verified against the arena layouts.
 *
 * The central balance lever is `ultChargeRate`: a fighter's ultimate power is
 * paid for in patience. Devastating ults charge slowly (Lenni's Kloten Kick,
 * 0.70 → ~79s passively; Jovan's Glorious Strike, 0.80), while modest ults
 * charge fast (Till's Sky Storm, 1.20 → ~46s). So a character can have a
 * game-ending ult *or* a weak ult with a great passive / special / normals
 * (Erim: modest Laser Barrage, but a counter passive AND life-draining Syphon
 * Pulse), and neither is strictly better — just a different rhythm to master.
 *
 * Adding a new fighter is just appending a config here.
 */
import type { FighterConfig } from '@/core/types';
import { makeAttack } from './attackTemplates';

export const FIGHTERS: FighterConfig[] = [
  {
    id: 'robin',
    name: 'Robin',
    role: 'All-Rounder',
    emoji: '🥊',
    blurb: 'Median stats across the board — the easiest fighter to learn.',
    personality: 'Steady, confident, never rattled.',
    passive: 'comboGrowth',
    passiveDescription: 'Each hit in a combo deals up to +40% more damage the longer it continues.',
    extraJumps: 1,
    ultChargeRate: 1.0,
    stats: { speed: 6.4, weight: 1.05, strength: 1.0, jumpHeight: 16.3, knockbackResist: 0.1 },
    appearance: {
      skin: '#f2c9a0',
      hair: '#e8c15a',
      hairStyle: 'short',
      eyes: '#5b3a1a',
      shirt: '#f5f2e8',
      pants: '#37508f',
      shoes: '#c8402f',
      build: 'normal',
      headband: '#ffd54a',
      gloves: '#c8402f',
      accent: '#ffd54a',
    },
    attacks: {
      light: makeAttack('light', {
        name: 'Quick Jab',
        description: 'A fast one-two that starts combos.',
      }),
      heavy: makeAttack('heavy', {
        name: 'Power Cross',
        description: 'A committed straight that launches at mid percent.',
      }),
      special: makeAttack('special', {
        name: 'Rapid Punches',
        description: 'A true flurry of quick blows — each jab racks up damage, low knockback until the last.',
        damage: 2.4,
        active: 0.5,
        hitInterval: 0.08,
        baseKnockback: 2,
        knockbackScaling: 0.06,
        angle: Math.PI * 0.1,
        cooldown: 1.2,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Golden Rush',
        description:
          'Robin ignites and charges across the stage, landing a blinding flurry on everyone in his path — the storm racks up damage early and launches for the kill once they are ripe.',
        damage: 6.5,
        hitInterval: 0.09,
        surge: true,
        active: 0.62,
        baseKnockback: 5,
        knockbackScaling: 0.28,
        reach: 1.9,
      }),
    },
  },
  {
    id: 'leif',
    name: 'Leif',
    role: 'Speedster',
    emoji: '💨',
    blurb: 'Fastest runner alive, but light and hits a little soft.',
    personality: 'Restless, playful, always moving.',
    passive: 'runSpeed',
    passiveDescription: 'Highest running speed on the roster; closes distance instantly.',
    extraJumps: 1,
    ultChargeRate: 0.9,
    stats: {
      speed: 8.0, weight: 0.88, strength: 0.9, jumpHeight: 16.8, knockbackResist: 0,
      airControl: 1.25,
    },
    appearance: {
      skin: '#e0a877',
      hair: '#5a3a22',
      hairStyle: 'spiky',
      eyes: '#8a8f96',
      shirt: '#1c1c1f',
      pants: '#3a3d45',
      shoes: '#38d0ff',
      build: 'lean',
      scarf: '#38d0ff',
      goggles: '#38d0ff',
      gloves: '#16161a',
      accent: '#38d0ff',
    },
    attacks: {
      light: makeAttack('light', {
        name: 'Snap Kick',
        description: 'A lightning jab kick — the fastest startup in the game.',
        startup: 0.05,
      }),
      heavy: makeAttack('heavy', {
        name: 'Spin Heel',
        description: 'A spinning heel kick with surprising launch power.',
      }),
      special: makeAttack('special', {
        name: 'Flying Kick',
        description: 'Leaps forward in a diagonal kick — great burst approach or finisher.',
        damage: 11,
        baseKnockback: 7,
        angle: Math.PI * 0.18,
        reach: 1.9,
        cooldown: 1.5,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Overdrive',
        description:
          "Leif redlines — for six seconds his attacks come out twice as fast and he blitzes around the stage even quicker than usual. No hit of its own; it turns his whole kit into a blur.",
        hasteSelf: { duration: 6, attackSpeed: 2, moveSpeed: 1.35 },
        damage: 0,
        active: 0,
        startup: 0.12,
        recovery: 0.25,
        baseKnockback: 0,
        knockbackScaling: 0,
        reach: 0,
        radius: 0,
        cooldown: 12,
      }),
    },
  },
  {
    id: 'jovan',
    name: 'Jovan',
    role: 'Zoner',
    emoji: '👑',
    blurb: 'Longest reach — controls space and pokes from just out of range.',
    personality: 'Calm, calculating, keeps his distance.',
    passive: 'reach',
    passiveDescription: 'All attacks reach noticeably farther than anyone else’s.',
    extraJumps: 1,
    ultChargeRate: 0.8,
    stats: { speed: 6.1, weight: 0.95, strength: 1.0, jumpHeight: 17.2, knockbackResist: 0.04 },
    appearance: {
      skin: '#e6bd97',
      hair: '#4a3320',
      hairStyle: 'long',
      eyes: '#5b3a1a',
      shirt: '#f4eedd',
      pants: '#2f4a35',
      shoes: '#25352a',
      build: 'normal',
      cape: '#1f3a2a',
      crown: true,
      shoulderPads: '#d4af37',
      accent: '#8affc1',
    },
    attacks: {
      light: makeAttack('light', {
        name: 'Long Jab',
        description: 'An extended straight that out-spaces most light attacks.',
        reach: 1.5,
      }),
      heavy: makeAttack('heavy', {
        name: 'Reach Strike',
        description: 'A far-reaching lunge punch that catches approaches.',
        reach: 1.8,
      }),
      special: makeAttack('special', {
        name: 'Roundhouse Spin',
        description: 'A wide spinning kick that sweeps a large arc around him.',
        damage: 10,
        reach: 2.1,
        angle: Math.PI * 0.24,
        cooldown: 1.6,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Glorious Strike',
        description:
          "A royal decree there is no dodging and no outrunning — Jovan advances with a sweeping cursed aura that rolls cannot pierce. Its touch loads the victim with +100% damage but no launch; only being airborne or on another platform keeps you safe.",
        damage: 100,
        noKnockback: true,
        piercesInvuln: true,
        surge: true,
        startup: 0.26,
        active: 0.42,
        recovery: 0.6,
        reach: 2.6,
        radius: 2.4,
        cooldown: 14,
      }),
    },
  },
  {
    id: 'leonidas',
    name: 'Leonidas',
    role: 'Tank',
    emoji: '🛡️',
    blurb: 'Heaviest and hardest to launch — an immovable wall that trades speed for staying power.',
    personality: 'Immovable, proud, speaks softly.',
    passive: 'knockbackArmor',
    passiveDescription: 'Takes 28% less knockback from every hit — survives to absurd percents.',
    extraJumps: 1,
    ultChargeRate: 0.85,
    stats: {
      speed: 5.0, weight: 1.5, strength: 1.12, jumpHeight: 15.4, knockbackResist: 0.3,
      airControl: 0.8, gravityMul: 1.04,
    },
    appearance: {
      skin: '#d9a273',
      hair: '#4a3320',
      hairStyle: 'styled',
      eyes: '#5b3a1a',
      shirt: '#8a2f2f',
      pants: '#3a2a1e',
      shoes: '#241812',
      build: 'heavy',
      scarf: '#ff7a3c',
      shoulderPads: '#b08d57',
      cape: '#5e1f1f',
      accent: '#ff7a3c',
    },
    attacks: {
      light: makeAttack('light', {
        name: 'Hook',
        description: 'A heavy hook — slower than most jabs but hits harder.',
        damage: 5,
      }),
      heavy: makeAttack('heavy', {
        name: 'Sledge',
        description: 'A crushing overhand that sends light fighters flying.',
        damage: 16,
        baseKnockback: 10,
        knockbackScaling: 0.36,
        startup: 0.22,
      }),
      special: makeAttack('special', {
        name: 'Ground Slam',
        description: 'Slams the ground, launching nearby foes straight up.',
        damage: 13,
        baseKnockback: 9,
        angle: Math.PI * 0.5,
        reach: 1.6,
        radius: 1.3,
        cooldown: 2,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Earthquake',
        description:
          'Shatters the ground itself — every opponent touching the stage is erupted skyward, no matter how far away. A brief rumble telegraphs it: jump in that window or be caught.',
        damage: 22,
        quake: true,
        startup: 0.34,
        baseKnockback: 13,
        knockbackScaling: 0.42,
        angle: Math.PI * 0.5,
        radius: 2.2,
        reach: 2.4,
      }),
    },
  },
  {
    id: 'erim',
    name: 'Erim',
    role: 'Counter-Puncher',
    emoji: '🧠',
    blurb: 'Durable and patient — punishes whiffs with counter-hits and drains health with Syphon Pulse.',
    personality: 'Patient, analytical, punishes mistakes.',
    passive: 'counterForce',
    passiveDescription: 'Hitting a foe who is mid-attack deals +32% knockback and +20% damage (counter-hit).',
    extraJumps: 1,
    ultChargeRate: 1.05,
    stats: { speed: 5.9, weight: 1.12, strength: 0.92, jumpHeight: 15.8, knockbackResist: 0.2 },
    appearance: {
      skin: '#cf9f74',
      hair: '#161616',
      hairStyle: 'goatee',
      eyes: '#5b3a1a',
      shirt: '#26355c',
      pants: '#1a2236',
      shoes: '#12161f',
      build: 'normal',
      pendant: true,
      accent: '#7c5cff',
      glasses: true,
      goatee: true,
    },
    attacks: {
      light: makeAttack('light', {
        name: 'Palm Jab',
        description: 'A crisp palm strike, best thrown to interrupt attackers.',
      }),
      heavy: makeAttack('heavy', {
        name: 'Counter Strike',
        description: 'A precise blow — devastating as a counter-hit thanks to his passive.',
      }),
      special: makeAttack('special', {
        name: 'Syphon Pulse',
        description:
          'A draining energy pulse — damage dealt syphons back, reducing his own damage %.',
        damage: 8,
        syphon: 0.6,
        baseKnockback: 5,
        angle: Math.PI * 0.35,
        reach: 1.5,
        cooldown: 2.4,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Laser Barrage',
        description:
          'Braces and unloads a volley of five energy bolts that streak across the whole stage, pelting foes toward the blast zone.',
        damage: 6,
        projectiles: { count: 5, speed: 26, interval: 0.09 },
        active: 0.5,
        baseKnockback: 6,
        knockbackScaling: 0.24,
        reach: 0.8,
        radius: 0.4,
        angle: Math.PI * 0.08,
      }),
    },
  },
  {
    id: 'till',
    name: 'Till',
    role: 'Acrobat',
    emoji: '🤸',
    blurb: 'Triple jump and the best air game — but frail and light-hitting.',
    personality: 'Bouncy, fearless, loves the air.',
    passive: 'tripleJump',
    passiveDescription: 'Jumps three times before landing — unmatched recovery and air control.',
    extraJumps: 2,
    ultChargeRate: 1.05,
    stats: {
      speed: 6.9, weight: 0.82, strength: 0.85, jumpHeight: 18.9, knockbackResist: 0,
      airControl: 1.4, gravityMul: 0.86,
    },
    appearance: {
      skin: '#f4d0aa',
      hair: '#efd35f',
      hairStyle: 'mohawk',
      eyes: '#3b6ea5',
      shirt: '#2f9a5a',
      pants: '#dfe6ec',
      shoes: '#6affea',
      build: 'lean',
      headband: '#6affea',
      kneePads: '#2f9a5a',
      accent: '#6affea',
    },
    attacks: {
      light: makeAttack('light', {
        name: 'Flip Jab',
        description: 'A nimble flipping jab that flows into aerials.',
        startup: 0.05,
      }),
      heavy: makeAttack('heavy', {
        name: 'Somersault',
        description: 'An acrobatic somersault kick that launches upward.',
      }),
      special: makeAttack('special', {
        name: 'Dive Kick',
        description: 'A steep dive kick from the air — spikes foes downward off ledges.',
        damage: 10,
        angle: -Math.PI * 0.25,
        reach: 1.5,
        cooldown: 1.3,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Sky Storm',
        description:
          'Till spirals into the sky, dragging anyone he clips upward with him — a rising cyclone that carries foes toward the top blast zone and launches them out of it at the peak.',
        damage: 6,
        hitInterval: 0.1,
        riseSelf: true,
        angle: Math.PI * 0.5,
        active: 0.62,
        baseKnockback: 8,
        knockbackScaling: 0.3,
      }),
    },
  },
  {
    id: 'lenni',
    name: 'Lenni',
    role: 'Technician',
    emoji: '⚙️',
    blurb: 'A glass cannon — fast and hard-hitting, but frail and floaty.',
    personality: 'Precise, focused, calls his shots.',
    passive: 'precision',
    passiveDescription: 'Heavy and special attacks land with +18% knockback when they connect cleanly.',
    extraJumps: 1,
    ultChargeRate: 0.7,
    stats: {
      speed: 6.6, weight: 0.98, strength: 1.12, jumpHeight: 16.9, knockbackResist: 0.06,
      gravityMul: 0.92,
    },
    appearance: {
      skin: '#ecc199',
      hair: '#6b4a2c',
      hairStyle: 'ponytail',
      eyes: '#5b3a1a',
      shirt: '#1f5e3a',
      pants: '#4a4a2c',
      shoes: '#2c2c1a',
      build: 'normal',
      backpack: '#2c3a30',
      accent: '#b6ff3c',
      glasses: true,
    },
    attacks: {
      light: makeAttack('light', {
        name: 'Precise Jab',
        description: 'A clean, reliable poke that sets up his stronger moves.',
      }),
      heavy: makeAttack('heavy', {
        name: 'Pinpoint Smash',
        description: 'A pinpoint smash with vicious knockback scaling — an early kill move.',
        knockbackScaling: 0.4,
      }),
      special: makeAttack('special', {
        name: 'Quick Dash Strike',
        description: 'Dashes forward with a precise strike — a fast, safe punish.',
        damage: 10,
        baseKnockback: 7,
        angle: Math.PI * 0.14,
        reach: 1.7,
        cooldown: 1.4,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Kloten Kick',
        description:
          'Launches high into the air, then a thunderous diving kick with a shockwave and extreme knockback — his signature.',
        damage: 32,
        baseKnockback: 20,
        knockbackScaling: 0.6,
        angle: Math.PI * 0.16,
        reach: 2.4,
        radius: 1.6,
        startup: 0.35,
        active: 0.28,
        cooldown: 14,
      }),
    },
  },
  {
    id: 'tusya',
    name: 'Tusya',
    role: 'Bruiser',
    emoji: '💥',
    blurb: 'Hits the hardest and hard to move — but the slowest on foot.',
    personality: 'Loud, relentless, hits like a truck.',
    passive: 'heavyStun',
    passiveDescription: 'Heavy attacks briefly stun on hit, guaranteeing a follow-up.',
    extraJumps: 1,
    ultChargeRate: 0.85,
    stats: {
      speed: 4.9, weight: 1.4, strength: 1.24, jumpHeight: 15.3, knockbackResist: 0.14,
      airControl: 0.85, gravityMul: 1.04,
    },
    appearance: {
      skin: '#6b4a34',
      hair: '#141414',
      hairStyle: 'buzz',
      eyes: '#4a2f1a',
      shirt: '#2c2930',
      pants: '#4a2020',
      shoes: '#1a1012',
      build: 'heavy',
      headband: '#ff4d6d',
      gloves: '#26222a',
      shoulderPads: '#443c48',
      accent: '#ff4d6d',
    },
    attacks: {
      light: makeAttack('light', {
        name: 'Heavy Jab',
        description: 'Even his jab hits like a normal fighter’s smash.',
        damage: 6,
      }),
      heavy: makeAttack('heavy', {
        name: 'Charge Punch',
        description: 'A booming punch that stuns on hit — the start of a brutal chain.',
        damage: 18,
        baseKnockback: 11,
        startup: 0.2,
      }),
      special: makeAttack('special', {
        name: 'Haymaker',
        description: 'Winds up a colossal haymaker that blasts foes clean across the stage.',
        damage: 14,
        baseKnockback: 10,
        startup: 0.28,
        reach: 1.6,
        cooldown: 1.8,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Meteor Smash',
        description:
          'A near-instant meteoric smash that spikes foes into the blast zone — barely any wind-up, so you must read it early and dodge on reaction.',
        damage: 30,
        baseKnockback: 19,
        startup: 0.16,
        angle: -Math.PI * 0.2,
        radius: 1.8,
      }),
    },
  },
];

/** Fast lookup of a fighter config by id. */
export const FIGHTER_BY_ID: Record<string, FighterConfig> = Object.fromEntries(
  FIGHTERS.map((f) => [f.id, f]),
);

/** Resolve a config, falling back to the first fighter for safety. */
export function getFighter(id: string): FighterConfig {
  return FIGHTER_BY_ID[id] ?? FIGHTERS[0];
}
