/**
 * The Modulo Fight roster.
 *
 * Each entry is a fully self-contained `FighterConfig`: appearance, stats,
 * passive, and the four attacks (light / heavy / special / ultimate). Adding a
 * new fighter is as simple as appending a config here — no other file needs to
 * change for the character to be selectable and playable.
 */
import type { FighterConfig } from '@/core/types';
import { makeAttack } from './attackTemplates';

export const FIGHTERS: FighterConfig[] = [
  {
    id: 'robin',
    name: 'Robin',
    role: 'Balanced',
    personality: 'Steady, confident, never rattled.',
    passive: 'comboGrowth',
    passiveDescription: 'Combo damage grows the longer a combo continues.',
    extraJumps: 1,
    stats: { speed: 6.4, weight: 1.0, strength: 1.0, jumpHeight: 17, knockbackResist: 0 },
    appearance: {
      skin: '#f2c9a0',
      hair: '#e8c15a',
      hairStyle: 'short',
      eyes: '#5b3a1a',
      shirt: '#f4f4f2',
      accent: '#ffd54a',
    },
    attacks: {
      light: makeAttack('light', { name: 'Quick Jab' }),
      heavy: makeAttack('heavy', { name: 'Power Cross' }),
      special: makeAttack('special', {
        name: 'Rapid Punches',
        damage: 2.4,
        active: 0.5,
        baseKnockback: 2,
        knockbackScaling: 0.06,
        angle: Math.PI * 0.1,
        cooldown: 1.2,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Golden Rush',
        damage: 30,
        baseKnockback: 18,
        reach: 2.2,
      }),
    },
  },
  {
    id: 'leif',
    name: 'Leif',
    role: 'Fast fighter',
    personality: 'Restless, playful, always moving.',
    passive: 'runSpeed',
    passiveDescription: 'Highest running speed on the roster.',
    extraJumps: 1,
    stats: { speed: 7.8, weight: 0.9, strength: 0.95, jumpHeight: 17.5, knockbackResist: 0 },
    appearance: {
      skin: '#e8b98c',
      hair: '#5a3a22',
      hairStyle: 'medium',
      eyes: '#8a8f96',
      shirt: '#1c1c1f',
      accent: '#38d0ff',
    },
    attacks: {
      light: makeAttack('light', { name: 'Snap Kick', startup: 0.05 }),
      heavy: makeAttack('heavy', { name: 'Spin Heel' }),
      special: makeAttack('special', {
        name: 'Flying Kick',
        damage: 11,
        baseKnockback: 7,
        angle: Math.PI * 0.18,
        reach: 1.9,
        cooldown: 1.5,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Hurricane Combo',
        damage: 24,
        active: 0.4,
        baseKnockback: 15,
      }),
    },
  },
  {
    id: 'jovan',
    name: 'Jovan',
    role: 'Range fighter',
    personality: 'Calm, calculating, keeps his distance.',
    passive: 'reach',
    passiveDescription: 'Longer melee reach than anyone else.',
    extraJumps: 1,
    stats: { speed: 6.2, weight: 0.95, strength: 1.0, jumpHeight: 16.5, knockbackResist: 0 },
    appearance: {
      skin: '#e6bd97',
      hair: '#4a3320',
      hairStyle: 'medium',
      eyes: '#5b3a1a',
      shirt: '#f4f4f2',
      accent: '#8affc1',
    },
    attacks: {
      light: makeAttack('light', { name: 'Long Jab', reach: 1.5 }),
      heavy: makeAttack('heavy', { name: 'Reach Strike', reach: 1.8 }),
      special: makeAttack('special', {
        name: 'Roundhouse Spin',
        damage: 10,
        reach: 2.1,
        angle: Math.PI * 0.24,
        cooldown: 1.6,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Cyclone Strike',
        damage: 25,
        reach: 2.6,
        active: 0.36,
      }),
    },
  },
  {
    id: 'leonidas',
    name: 'Leonidas',
    role: 'Tank',
    personality: 'Immovable, proud, speaks softly.',
    passive: 'knockbackArmor',
    passiveDescription: 'Takes reduced knockback from all hits.',
    extraJumps: 1,
    stats: { speed: 5.2, weight: 1.5, strength: 1.15, jumpHeight: 14.5, knockbackResist: 0.28 },
    appearance: {
      skin: '#eabf95',
      hair: '#4a3320',
      hairStyle: 'styled',
      eyes: '#5b3a1a',
      shirt: '#7a2f2f',
      accent: '#ff7a3c',
    },
    attacks: {
      light: makeAttack('light', { name: 'Hook', damage: 5 }),
      heavy: makeAttack('heavy', {
        name: 'Sledge',
        damage: 16,
        baseKnockback: 10,
        knockbackScaling: 0.36,
        startup: 0.22,
      }),
      special: makeAttack('special', {
        name: 'Ground Slam',
        damage: 13,
        baseKnockback: 9,
        angle: Math.PI * 0.5,
        reach: 1.6,
        radius: 1.3,
        cooldown: 2,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Earthquake',
        damage: 28,
        radius: 2.2,
        reach: 2.4,
        angle: Math.PI * 0.45,
      }),
    },
  },
  {
    id: 'erim',
    name: 'Erim',
    role: 'Defensive strategist',
    personality: 'Patient, analytical, punishes mistakes.',
    passive: 'counterForce',
    passiveDescription: 'Counter-hits deal extra knockback.',
    extraJumps: 1,
    stats: { speed: 5.9, weight: 1.05, strength: 0.95, jumpHeight: 16, knockbackResist: 0.08 },
    appearance: {
      skin: '#e0b48a',
      hair: '#161616',
      hairStyle: 'goatee',
      eyes: '#5b3a1a',
      shirt: '#2b3a55',
      accent: '#7c5cff',
      glasses: true,
      goatee: true,
    },
    attacks: {
      light: makeAttack('light', { name: 'Palm Jab' }),
      heavy: makeAttack('heavy', { name: 'Counter Strike' }),
      special: makeAttack('special', {
        name: 'Energy Shield',
        damage: 6,
        baseKnockback: 5,
        angle: Math.PI * 0.35,
        reach: 1.4,
        cooldown: 2.4,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Laser Barrage',
        damage: 22,
        active: 0.5,
        reach: 2.4,
        angle: Math.PI * 0.1,
      }),
    },
  },
  {
    id: 'till',
    name: 'Till',
    role: 'Acrobat',
    personality: 'Bouncy, fearless, loves the air.',
    passive: 'tripleJump',
    passiveDescription: 'Can jump three times before landing.',
    extraJumps: 2,
    stats: { speed: 6.8, weight: 0.85, strength: 0.9, jumpHeight: 18, knockbackResist: 0 },
    appearance: {
      skin: '#f2c9a0',
      hair: '#efd35f',
      hairStyle: 'short',
      eyes: '#3b6ea5',
      shirt: '#2f7a4f',
      accent: '#6affea',
    },
    attacks: {
      light: makeAttack('light', { name: 'Flip Jab', startup: 0.05 }),
      heavy: makeAttack('heavy', { name: 'Somersault' }),
      special: makeAttack('special', {
        name: 'Dive Kick',
        damage: 10,
        angle: -Math.PI * 0.25,
        reach: 1.5,
        cooldown: 1.3,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Sky Storm',
        damage: 23,
        angle: Math.PI * 0.4,
        active: 0.4,
      }),
    },
  },
  {
    id: 'lenni',
    name: 'Lenni',
    role: 'Technical fighter',
    personality: 'Precise, focused, calls his shots.',
    passive: 'precision',
    passiveDescription: 'Precision attacks land with increased knockback.',
    extraJumps: 1,
    stats: { speed: 6.5, weight: 1.0, strength: 1.05, jumpHeight: 16.8, knockbackResist: 0 },
    appearance: {
      skin: '#ecc199',
      hair: '#6b4a2c',
      hairStyle: 'medium',
      eyes: '#5b3a1a',
      shirt: '#26402c',
      accent: '#b6ff3c',
      glasses: true,
    },
    attacks: {
      light: makeAttack('light', { name: 'Precise Jab' }),
      heavy: makeAttack('heavy', { name: 'Pinpoint Smash', knockbackScaling: 0.4 }),
      special: makeAttack('special', {
        name: 'Quick Dash Strike',
        damage: 10,
        baseKnockback: 7,
        angle: Math.PI * 0.14,
        reach: 1.7,
        cooldown: 1.4,
      }),
      ultimate: makeAttack('ultimate', {
        // Signature: leaps skyward, then a diving kick with huge knockback.
        name: 'Kloten Kick',
        damage: 32,
        baseKnockback: 20,
        knockbackScaling: 0.6,
        angle: Math.PI * 0.16,
        reach: 2.4,
        radius: 1.6,
        startup: 0.35,
        active: 0.28,
        cooldown: 14,
      }),
    },
  },
  {
    id: 'tusya',
    name: 'Tusya',
    role: 'Heavy striker',
    personality: 'Loud, relentless, hits like a truck.',
    passive: 'heavyStun',
    passiveDescription: 'Heavy attacks briefly stun on hit.',
    extraJumps: 1,
    stats: { speed: 5.5, weight: 1.35, strength: 1.2, jumpHeight: 15, knockbackResist: 0.12 },
    appearance: {
      skin: '#6b4a34',
      hair: '#141414',
      hairStyle: 'short',
      eyes: '#4a2f1a',
      shirt: '#37343b',
      accent: '#ff4d6d',
    },
    attacks: {
      light: makeAttack('light', { name: 'Heavy Jab', damage: 6 }),
      heavy: makeAttack('heavy', {
        name: 'Charge Punch',
        damage: 18,
        baseKnockback: 11,
        startup: 0.2,
      }),
      special: makeAttack('special', {
        name: 'Charge Punch',
        damage: 14,
        baseKnockback: 10,
        startup: 0.28,
        reach: 1.6,
        cooldown: 1.8,
      }),
      ultimate: makeAttack('ultimate', {
        name: 'Meteor Smash',
        damage: 30,
        baseKnockback: 19,
        angle: -Math.PI * 0.2,
        radius: 1.8,
      }),
    },
  },
];

/** Fast lookup of a fighter config by id. */
export const FIGHTER_BY_ID: Record<string, FighterConfig> = Object.fromEntries(
  FIGHTERS.map((f) => [f.id, f]),
);

/** Resolve a config, falling back to the first fighter for safety. */
export function getFighter(id: string): FighterConfig {
  return FIGHTER_BY_ID[id] ?? FIGHTERS[0];
}
